# .github/workflows/main.yml for texlive-source CI building
#
# Norbert Preining
# Public Domain
#
# This file controls CI testing via Github Actions of the
# git-svn checkout of the TeX Live source directory
# which is pushed to Github
#   https://github.com/TeX-Live/texlive-source
# The cron job that does the git svn up and git push is
# running on texlive.info; see norbert cron there. Run cmd as norbert:
#   /home/norbert/git-svn-repos/git-svn-syncer --new texlive-source
#
# To make and retrieve new binaries:
# * go to https://github.com/TeX-Live/texlive-source/commits/master
#   and check that all commits you want are there (max waiting time 30min).
# * go to https://github.com/TeX-Live/texlive-source/releases
#   and "Draft new release" (does git tag).
# * wait 30min or so.
# * go to https://github.com/TeX-Live/texlive-source/releases/latest/
#   and there should be binaries for the new "release".
# * use tl-update-bindir.
#
# The actual code for building and running is in the Github Action
#   TeX-Live/tl-build-docker-action
#
# TODO
# * it would be nice if we could adjust the docker action usage
#   to override the dockerfile but this seems not to be possible at the moment

on: [push]


jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.tl_name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - tl_name: i386-linux
            image: i386/ubuntu:xenial
            arch: 386
          - tl_name: x86_64-linux
            image: centos:7
            arch: amd64
          - tl_name: x86_64-linuxmusl
            image: alpine:3.5
            arch: amd64
          - arch: aarch64
            image: arm64v8/debian:buster
            tl_name: aarch64-linux

    steps:
      - name: checkout-main
        uses: actions/checkout@v4
        with:
          path: 'repo'
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}
      - name: build
        uses: addnab/docker-run-action@v3
        with: 
          image: ${{ matrix.image }}
          options: -v ${{ github.workspace }}:/work --platform linux/${{ matrix.arch }}
          run: |
            cd /work/repo
            case "${{ matrix.image }}" in
              i386/ubuntu:*) .github/scripts/install-deps.ubuntu.sh ;;
              centos:*) .github/scripts/install-deps.centos.sh ;;
              alpine:*) .github/scripts/install-deps.alpine.sh ;;
            esac
            .github/scripts/build-tl.sh ${{ matrix.tl_name }}
      - name: find file step
        run: ls -l . repo $GITHUB_WORKSPACE
      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: texlive-bin-${{ matrix.arch }}.tar.gz
          path: ${{ github.workspace }}/repo/texlive-bin-${{ matrix.arch }}.tar.gz
          compression-level: 0
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $GITHUB_WORKSPACE/repo/texlive-bin-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_job_qemu:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: buster
            tl_name: aarch64-linux
          - arch: armv7
            distro: buster
            tl_name: armhf-linux
    steps:
      - name: checkout-main
        uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "/tmp/artifacts"
          dockerRunArgs: |
            --volume "/tmp/artifacts:/artifacts"
          env: |
            arch: ${{ matrix.arch }}
            distro: ${{ matrix.distro }}
          shell: /bin/bash
          install: |
            # this does not work because during install the
            # checkout is not available!!!
            # https://github.com/uraimo/run-on-arch-action/issues/54
            # case "${{ matrix.distro }}" in
            #   buster) .github/scripts/install-deps.ubuntu.sh ;;
            # esac
            case "${{ matrix.distro }}" in
              buster)
               export DEBIAN_FRONTEND=noninteractive
               export LANG=C.UTF-8
               export LC_ALL=C.UTF-8
               apt-get update -q -y
               apt-get install -y --no-install-recommends bash gcc g++ make perl libfontconfig-dev libx11-dev libxmu-dev libxaw7-dev build-essential
               ;;
            esac
          run: .github/scripts/build-tl.sh ${{ matrix.tl_name }} /artifacts
      - name: find file step
        run: |
          ls -d /tmp/artifacts
          ls -l /tmp/artifacts
      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: texlive-bin-${{ matrix.tl_name }}.tar.gz
          path: /tmp/artifacts/texlive-bin-${{ matrix.tl_name }}.tar.gz
          compression-level: 0
          retention-days: 5
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/artifacts/texlive-bin-${{ matrix.tl_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
